### ISSUE TITLE
Error: expected an implementation for 6

### ISSUE THREAD

**Issue by nizarayari** [CoachLogix/ember-paper-stepper#2]
Hi there, we are using emblem for templating and ran into this error for this template:
```
= paper-stepper currentStep=0 onStepChange=(action (mut currentStep)) onStepperCompleted=(route-action "saveModel") as |stepper|
        = stepper.step label="Select how it looks" as |step|
          = step.body
          = step.actions as |nextStep previousStep|
            = paper-button primary=true raised=true onClick=(action nextStep)
              Continue
            = paper-button onClick=(action previousStep)
              Back
```
It's probably an issue with ember-paper.
Did anyone had this issue?

**Comment by miguelcobain** [comment]
@nizarayari Sorry, where exactly is the error?

**Comment by miguelcobain** [comment]
Ah, the title "Error: expected an implementation for 6".

Yes, this is an issue with ember 2.13 at the moment. Basically any tag that contains a dash errors now. If you downgrade to 2.12 for the time being, it should fix the problem.

**Comment by miguelcobain** [comment]
x-ref https://github.com/miguelcobain/ember-paper/issues/705

**Comment by nizarayari** [comment]
I already upgraded to 2.13. I still have the issue

**Comment by miguelcobain** [comment]
@nizarayari what I suggested was to **downgrade** to 2.12.
