### ISSUE TITLE
I can not go directly to any step despite linear='false'

### ISSUE THREAD

**Issue by syedasadhasan** [CoachLogix/ember-paper-stepper#8]
What could be the reason. linear property is set to false still it is not enabling click to any step.

  {{#paper-stepper
    currentStep=currentStep 
    linear = "false" 
    onStepChange=(action (mut currentStep))
    onStepperCompleted=(action "stepperCompleted") as |stepper|}}

**Comment by mohitsud** [comment]
its because you have the word false in quotes.

simply add linear=false without quotes

`{{#paper-stepper
currentStep=currentStep
linear = false
onStepChange=(action (mut currentStep))
onStepperCompleted=(action "stepperCompleted") as |stepper|}}`
